/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sulthonythaitea;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fahmi Sulthoni 17111042
 */
public class SulthonythaiteaForm extends javax.swing.JFrame {
    char type;
    DefaultTableModel tableModel;
    
    String menu;
    long hargasatuan=0, jumlahb=0, total=0, totalbayar=0, kembali=0, totalpisan=0, totalbanget=0;
    DecimalFormat df = new DecimalFormat("#,###");
    /**
     * Creates new form TulisKuForm
     */
    public SulthonythaiteaForm() {
        initComponents();
        long noTransaksi = System.currentTimeMillis();
        notransaksi.setText(String.valueOf(noTransaksi));
        tableModel = (DefaultTableModel) tabelpesanan.getModel();
        tableModel.setRowCount(0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listmenu = new javax.swing.JList<>();
        jumlah = new javax.swing.JTextField();
        tambahkan = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelpesanan = new javax.swing.JTable();
        resettabel = new javax.swing.JButton();
        deletetabel = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        harga = new javax.swing.JLabel();
        diskon = new javax.swing.JLabel();
        totalharga = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        notransaksi = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jbayar = new javax.swing.JTextField();
        bayar = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        cash = new javax.swing.JCheckBox();
        debit = new javax.swing.JCheckBox();
        jLabel15 = new javax.swing.JLabel();
        kembalian = new javax.swing.JLabel();
        keluar = new javax.swing.JButton();
        resetall = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("SulthonyThaiTea");
        setAlwaysOnTop(true);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SulthonyThaiTea");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(237, 237, 237)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(34, 34, 34))
        );

        jPanel3.setBackground(new java.awt.Color(0, 255, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu"));

        listmenu.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Thai Iced Tea", "Thai Iced Green Tea", "Thai Iced Coffee", "Thai Iced Ovaltine", "Thai Iced Ovaltine Coffee", "Thai Pink Rose", "Truffle Chocolate", "Creamy Red Velvet", "Milo", "Milo Coffee" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listmenu);

        jumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jumlahKeyTyped(evt);
            }
        });

        tambahkan.setText("Tambahkan");
        tambahkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahkanActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(tambahkan)))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tambahkan))
        );

        jPanel4.setBackground(new java.awt.Color(0, 255, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Keranjang Minuman"));

        tabelpesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Menu", "Harga Satuan", "Jumlah Pesanan", "Total Harga"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Long.class, java.lang.Long.class, java.lang.Long.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tabelpesanan);

        resettabel.setText("Reset");
        resettabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resettabelActionPerformed(evt);
            }
        });

        deletetabel.setText("Delete");
        deletetabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deletetabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 556, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(deletetabel, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resettabel, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deletetabel)
                    .addComponent(resettabel))
                .addContainerGap())
        );

        jPanel5.setBackground(new java.awt.Color(0, 255, 204));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Ketentuan"));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("1. Untuk minuman Thai Pink Rose jika pembeli membeli barang tersebut lebih dari 1,");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("maka harga satuan minuman tersebut menjadi Rp25.000,-/pcs.");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("2. Jika pembeli menggunakan debit maka akan mendapat diskon sebesar 10%");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("dari total bayar");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 496, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 483, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(0, 255, 204));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Total Harga"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Harga");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Diskon");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Total Harga");

        harga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        harga.setText("0");

        diskon.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        diskon.setText("0");

        totalharga.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        totalharga.setText("0");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel12.setText("No Transaksi");

        notransaksi.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        notransaksi.setText("-");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setText("Bayar");

        jbayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbayarActionPerformed(evt);
            }
        });
        jbayar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jbayarKeyTyped(evt);
            }
        });

        bayar.setText("Bayar");
        bayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bayarActionPerformed(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(0, 255, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder("Metode Pembayaran"));

        cash.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cash.setText("Cash");
        cash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashActionPerformed(evt);
            }
        });

        debit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        debit.setText("Debit");
        debit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                debitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(debit, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cash, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(cash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(debit)
                .addGap(18, 18, 18))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel15.setText("Kembalian");

        kembalian.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        kembalian.setText("0");

        keluar.setText("Keluar");
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });

        resetall.setText("Reset");
        resetall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(notransaksi)
                            .addComponent(harga)
                            .addComponent(diskon)
                            .addComponent(totalharga)))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(keluar, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(resetall, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel6Layout.createSequentialGroup()
                                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel14))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbayar, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kembalian)
                                    .addGroup(jPanel6Layout.createSequentialGroup()
                                        .addGap(38, 38, 38)
                                        .addComponent(bayar)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(notransaksi))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(harga))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(diskon))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(totalharga))
                .addGap(18, 18, 18)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jbayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(bayar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(kembalian))
                        .addGap(14, 14, 14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetall)
                    .addComponent(keluar))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void resettabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resettabelActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, "Apakah anda yakin?", 
                "Confirm Dialog",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
        tableModel = (DefaultTableModel) tabelpesanan.getModel();
        tableModel.setRowCount(0);
        listmenu.clearSelection();
        harga.setText("0");
        }
    }//GEN-LAST:event_resettabelActionPerformed

    private void cashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashActionPerformed
        // TODO add your handling code here:
        if(cash.isSelected()){
            diskon.setText("0");
            totalharga.setText("Rp"+df.format(totalbayar)+",-");
        }
    }//GEN-LAST:event_cashActionPerformed

    private void jbayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbayarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbayarActionPerformed

    private void jumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jumlahKeyTyped
        type = evt.getKeyChar();
        if(jumlah.getText().length() > 1 || !Character.isDigit(type)){
            evt.consume();
        }       
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahKeyTyped

    private void tambahkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahkanActionPerformed
        // TODO add your handling code here:
        int errors = 0;
        String psn = "Harap isi Form dengan benar \n";
        
        if (listmenu.isSelectionEmpty()){
            psn += "   - Menu belum dipilih, silahkan pilih dulu \n";
            errors += 1;
        }
        
        if (jumlah.getText().isEmpty()){
            psn += "   - Jumlah pesanan belum diidsi, silahkan isi dulu \n";
            errors += 1;
        }
        
        if(errors == 0){
        
        if(!jumlah.getText().isEmpty() && !listmenu.isSelectionEmpty()){
            if(listmenu.getSelectedValue().toString().equals("Thai Iced Tea")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 19000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
                
            }
        }if(listmenu.getSelectedValue().toString().equals("Thai Iced Green Tea")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 20000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Thai Iced Coffee")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 19000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Thai Iced Ovaltine")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 24000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Thai Iced Ovaltine Coffee")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 25000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Thai Pink Rose")){
                menu = listmenu.getSelectedValue().toString();
                jumlahb = Long.parseLong(jumlah.getText());
                int a = Integer.parseInt(jumlah.getText());
                if(a>1){
                    hargasatuan = 25000;
                }if(a<=1){  
                    hargasatuan = 28000;
                }
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Truffle Chocolate")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 21000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Creamy Red Velvet")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 24000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Milo")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 19000;
                jumlahb = Long.parseLong(jumlah.getText());
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        if(listmenu.getSelectedValue().toString().equals("Milo Coffee")){
                menu = listmenu.getSelectedValue().toString();
                hargasatuan = 21000;
                if(jumlahb > 50){
                    jumlah.setText("");
                    JOptionPane.showMessageDialog(this, "Maaf jumlah pesanan tidak boleh lebih dari 50 pcs", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                }
                if(jumlahb < 50){
                    total = hargasatuan * jumlahb;
                    Object[] data = {menu, hargasatuan, jumlahb, total};
                    tableModel.addRow(data);
                }
            }
        }else{
            JOptionPane.showMessageDialog(null, psn);
        }
  
        long tempTotalBayar=0;
             for(int i=0; i<tableModel.getRowCount(); i++){
                 tempTotalBayar = tempTotalBayar+Long.parseLong(tableModel.getValueAt(i,3).toString());
                 totalbayar = tempTotalBayar;
             }
        harga.setText("Rp"+df.format(totalbayar)+",-");
        jumlah.setText("");
        
    }//GEN-LAST:event_tambahkanActionPerformed

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, "Apakah anda yakin?", 
                "Confirm Dialog",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
            JOptionPane.showMessageDialog(this, "Program selesai");
            System.exit(0);
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void deletetabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deletetabelActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) tabelpesanan.getModel();        
            int SelectedRowIndex = tabelpesanan.getSelectedRow();
            if(SelectedRowIndex<0){
                JOptionPane.showMessageDialog(this, "Silahkan pilih barang yang akan di hapus!", "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
            if(SelectedRowIndex>=0){
                if(JOptionPane.showConfirmDialog(this,"Anda yakin untuk menghapus?","Konfirmasi Dialog",JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE)==0){
                    JOptionPane.showMessageDialog(this, "Data berhasil di hapus");
                    model.removeRow(SelectedRowIndex);                    
                }                   
            }
    }//GEN-LAST:event_deletetabelActionPerformed

    private void jbayarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jbayarKeyTyped
        // TODO add your handling code here:
        type=evt.getKeyChar();
        if(!Character.isDigit(type)){
            evt.consume();
        }
    }//GEN-LAST:event_jbayarKeyTyped

    private void bayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bayarActionPerformed
        // TODO add your handling code here:
        if(jbayar.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Jumlah uang belum diisi, silahkan isi terlebih dahulu",
            "Informasi", JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(cash.isSelected()){
            int b = Integer.parseInt(jbayar.getText());
            int a = (int) totalbayar;
            if(b>a){
            int c = b - a;
            kembalian.setText("Rp"+df.format(c)+",-");
            }else{
            JOptionPane.showMessageDialog(null, "Maaf jumlah uang tidak cukup",
            "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }else if(debit.isSelected()){
            int b = Integer.parseInt(jbayar.getText());
            int a = (int) totalbanget;
            if(b>a){
            int c = b - a;
            kembalian.setText("Rp"+df.format(c)+",-");
            }else{
            JOptionPane.showMessageDialog(null, "Maaf jumlah uang tidak cukup",
            "Informasi", JOptionPane.INFORMATION_MESSAGE);
            }
        }
        
    }//GEN-LAST:event_bayarActionPerformed

    private void resetallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetallActionPerformed
        // TODO add your handling code here:
        int jawab = JOptionPane.showOptionDialog(this, "Apakah anda yakin?", 
                "Confirm Dialog",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE, null, null, null);
        
        if(jawab == JOptionPane.YES_OPTION){
        tableModel = (DefaultTableModel) tabelpesanan.getModel();
        tableModel.setRowCount(0);
        listmenu.clearSelection();
        cash.setSelected(false);
        debit.setSelected(false);
        harga.setText("0");
        diskon.setText("0");
        totalharga.setText("0");
        jbayar.setText("0");
        kembalian.setText("Rp0,-");
        }
    }//GEN-LAST:event_resetallActionPerformed

    private void debitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_debitActionPerformed
        // TODO add your handling code here:
        if(debit.isSelected()){
            totalpisan = (long) (totalbayar * 0.10);
        }
        diskon.setText("Rp"+df.format(totalpisan)+",-");
        totalbanget = totalbayar - totalpisan;
        totalharga.setText("Rp"+df.format(totalbanget)+",-");
    }//GEN-LAST:event_debitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SulthonythaiteaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SulthonythaiteaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SulthonythaiteaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SulthonythaiteaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
    
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SulthonythaiteaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bayar;
    private javax.swing.JCheckBox cash;
    private javax.swing.JCheckBox debit;
    private javax.swing.JButton deletetabel;
    private javax.swing.JLabel diskon;
    private javax.swing.JLabel harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jbayar;
    private javax.swing.JTextField jumlah;
    private javax.swing.JButton keluar;
    private javax.swing.JLabel kembalian;
    private javax.swing.JList<String> listmenu;
    private javax.swing.JLabel notransaksi;
    private javax.swing.JButton resetall;
    private javax.swing.JButton resettabel;
    private javax.swing.JTable tabelpesanan;
    private javax.swing.JButton tambahkan;
    private javax.swing.JLabel totalharga;
    // End of variables declaration//GEN-END:variables

}
